<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CityGeneration.Contracts\CityGeneration.Contracts.csproj" />
      <ProjectReference Include="..\CityGeneration.Core.Data\CityGeneration.Core.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Blazor.Extensions.Canvas" Version="1.1.1" />
    </ItemGroup>

</Project>
