<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CityGeneration.Contracts.gRPC\CityGeneration.Contracts.gRPC.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
    </ItemGroup>

</Project>
